"""empty message

Revision ID: 41421dbcfe49
Revises: cb4102d9df9d
Create Date: 2020-02-09 12:01:25.524872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41421dbcfe49'
down_revision = 'cb4102d9df9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID валюты'),
    sa.Column('question', sa.String(), nullable=False, comment='Вопрос'),
    sa.Column('answer', sa.String(), nullable=False, comment='Ответ'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogs')
    # ### end Alembic commands ###
