"""empty message

Revision ID: a8254de3dfdd
Revises: c1557037736e
Create Date: 2020-02-09 14:22:23.936040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import models

revision = 'a8254de3dfdd'
down_revision = 'c1557037736e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogs', sa.Column('vector', models.db.NDArray(), nullable=False, comment='Векторы признаков фото'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialogs', 'vector')
    # ### end Alembic commands ###
