"""empty message

Revision ID: c1557037736e
Revises: 41421dbcfe49
Create Date: 2020-02-09 14:13:56.191911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1557037736e'
down_revision = '41421dbcfe49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
