"""empty message

Revision ID: cb4102d9df9d
Revises: 
Create Date: 2020-02-08 23:28:57.892128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
import models

revision = 'cb4102d9df9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_similarity"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='ID валюты'),
    sa.Column('name', sa.String(), nullable=False, comment='Название фото'),
    sa.Column('vector', models.db.NDArray(), nullable=False, comment='Векторы признаков фото'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
